# Generated by Django 3.0.7 on 2021-03-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular', models.CharField(max_length=12)),
                ('rut', models.CharField(max_length=12)),
                ('group', models.CharField(max_length=100)),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Comidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('detalle', models.CharField(max_length=300)),
                ('flag', models.BooleanField()),
                ('fecha', models.DateField()),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comida', models.IntegerField()),
                ('id_cliente', models.IntegerField()),
                ('fecha', models.DateField()),
                ('vigente', models.BooleanField()),
            ],
        ),
    ]
