# Generated by Django 3.0.7 on 2021-03-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionClientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidas',
            name='fecha',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha',
            field=models.TimeField(),
        ),
    ]
