# Generated by Django 3.0.7 on 2021-03-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionClientes', '0002_auto_20210302_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidas',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
