# Generated by Django 3.0.7 on 2021-03-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionClientes', '0003_auto_20210302_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_platos', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Platos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('tipo', models.BooleanField()),
                ('vigente', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Comidas',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='detalle',
            field=models.CharField(default=1, max_length=300, verbose_name='nada'),
            preserve_default=False,
        ),
    ]
