# Generated by Django 3.0.7 on 2021-03-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionClientes', '0004_auto_20210303_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='detalle',
            field=models.CharField(max_length=300),
        ),
    ]
