# Generated by Django 3.0.7 on 2021-03-07 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionClientes', '0006_auto_20210304_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='id_comida',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='date',
            field=models.DateField(default='2021-03-07'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidos',
            name='opcion',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
