# Generated by Django 3.0.7 on 2021-03-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionClientes', '0007_auto_20210307_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tope', models.IntegerField()),
                ('automatico', models.BooleanField()),
            ],
        ),
    ]
